spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlinepruf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  spring:
    jackson:
      serialization:
        write_dates_as_timestamps=false


  http:
    multipart:
      enabled=false:


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
